### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [scgywx/fooking#2]
Would you like to add more error handling for return values from functions like the following?
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html) ⇒ [Master::setupSignal](https://github.com/scgywx/fooking/blob/2cb6e4cf93c6ea7e6e103df50d38de0f3ead5a44/src/Master.cpp#L136)
- [write](http://pubs.opengroup.org/onlinepubs/9699919799/functions/write.html) ⇒ [Log::write](https://github.com/scgywx/fooking/blob/71149744e1da3b4900d3c74332d4e2ec7f9739bc/src/Log.cpp#L35)

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html) a bit more.
Would you like to detect every error situation as early as possible?

**Comment by scgywx** [comment]
thanks for your suggest.
Master::setupSignal add return value is okay.
but Log::write add the return value will no meaning,because cannot terminal programa when write return -1.

Also,Redis and Nginx source code did not do that.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B) also for your software?
