### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [scgywx/fooking#3]
[The function "LOG_INFO"](https://github.com/scgywx/fooking/blob/3ddc9e46473287ca894a63a2adba2e80f8b8e90d/src/Log.h#L19) does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).
I guess that a different program design will be needed for your function "[Master::procSignal](https://github.com/scgywx/fooking/blob/2cb6e4cf93c6ea7e6e103df50d38de0f3ead5a44/src/Master.cpp#L151)".

**Comment by scgywx** [comment]
the step is LOG_INFO -> Log::write -> write.
so "write" already in the list of async-signal-safe functions.
isn't it?

**Comment by elfring** [comment]
Does [the implementation of the member function "Log::write"](https://github.com/scgywx/fooking/blob/71149744e1da3b4900d3c74332d4e2ec7f9739bc/src/Log.cpp#L35) call any functions (like "gettimeofday") which are [async-signal-unsafe](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers)?

**Comment by scgywx** [comment]
Ok, you are right.
The implementation of the redis-server is to add another log message function for signal handle, only invoke time and write, so it's safely.

I had 2 ways to resolve the problem:
1. removed the log message from this signal handle,
2. add another log message function for this signal handle(only invoke time and write).

**Comment by elfring** [comment]
Would you like to consider other software design options?
- [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)
- [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/)

**Comment by scgywx** [comment]
Ok, thanks.

**Comment by scgywx** [comment]
The codes of signal handle moved to main loop.

**Comment by scgywx** [comment]
Modify the data type to sig_atomic_t, thank you.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/scgywx/fooking/commit/d73ffa5ff7aad9c978d78fc8afcf2419dc1fc76d).
