### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [scgywx/fooking#4]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/scgywx/fooking/blob/3255091d3e42400bb2fb8b9660517b47cf09d6bb/Makefile#L1) so that powerful checks for software features will become easier.
- [CMake](http://cmake.org/)
- [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction)

**Comment by scgywx** [comment]
thanks for your suggestion.
